### ISSUE TITLE
Ordine delle colonne

### ISSUE THREAD

**Issue by giuragu** [cirospat/pnrr_2021_opendata#1]
Ciao @cirospat 
intanto grazie per questa possibilità di consultazione del PNRR.
Avrei una proposta che ovviamente sei libero di rifiutare del tutto, accettare in parte, accettare.

Per rispecchiare il senso logico e una lettura, per riga, da sinistra verso destra, trovo più "leggibile" e comprensibile l'ordinamento delle colonne in questo modo: missioni, componenti, ambiti di intervento, investimenti e riforme, spesa (da sinistra verso destra)

Che ne pensi?

**Comment by cirospat** [comment]
ciao @giuragu 

penso che leggere subito da sinistra 14 volte la stessa  cosa (missioni) sia annoiante.
Per questo subito ho messo a sx il titolo intervento che è diverso per tutti i 136 interventi.
Infatti il link è agganciato al titolo sempre diverso.

**Comment by giuragu** [comment]
Ok @cirospat
Chiudo issue. E ancora grazie
